---

- name: RedHat | Install dependencies packages
  yum: name={{ item }} state=installed
  with_items: "{{ mongodb_packages_dependencies }}"

- name: RedHat | Add source sources
  template: src=mongodb.repo.j2 dest=/etc/yum.repos.d/mongodb.repo
  register: sources

- name: Reload yum after sources change
  shell: yum clean metadata
  when: sources|changed

- name: RedHat | Install Packages
  yum: name={{ item }} state=installed
  with_items: "{{ mongodb_packages }}"
